trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Build and Publish'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'hcalculator-SC'
    appType: 'webAppLinux'
    appName: 'hcalculator'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'